spring:
  application:
    name: itoken-service-redis
  boot:
    admin:
      client:
        url: http://192.168.33.131:8084
  zipkin:
    base-url: http://192.168.33.131:9411

fastdfs.base.url: http://192.168.33.131:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 192.168.33.131:22122

server:
  port: 8505

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.33.131:8761/eureka/, http://192.168.33.131:8861/eureka/, http://192.168.33.131:8961/eureka/

  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.33.131:26379, 192.168.33.131:26380, 192.168.33.131:26381

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info